export const queries = [
    { query: "looking for sushi restaurants in colombo 1", fetched: false },
    { query: "find fine dining restaurants in colombo 1", fetched: false },
    { query: "luxury hotel buffets in colombo 1", fetched: false },
    { query: "romantic dinner restaurants in colombo 1", fetched: false },
    { query: "best French restaurants for dinner in colombo 1", fetched: false },
    { query: "Italian fine dining in colombo 1", fetched: false },
    { query: "upscale seafood restaurants in colombo 2", fetched: false },
    { query: "steakhouse restaurants with reservation in colombo 2", fetched: false },
    { query: "best international cuisine restaurants in colombo 2", fetched: false },
    { query: "Japanese dinner restaurants in colombo 2", fetched: false },
    { query: "best Thai restaurants for dinner in colombo 2", fetched: false },
    { query: "fine dining Chinese restaurants colombo 2", fetched: false },
    { query: "fine dining restaurants for dinner in colombo 3", fetched: false },
    { query: "hotel buffet dinner options in colombo 3", fetched: false },
    { query: "luxury rooftop restaurants in colombo 3", fetched: false },
    { query: "Italian dinner restaurants in colombo 3", fetched: false },
    { query: "best Mediterranean restaurants for dinner in colombo 3", fetched: false },
    { query: "French cuisine fine dining in colombo 3", fetched: false },
    { query: "exclusive dinner restaurants in colombo 4", fetched: false },
    { query: "best hotel buffets in colombo 4", fetched: false },
    { query: "romantic dining restaurants in colombo 4", fetched: false },
    { query: "Japanese fine dining in colombo 4", fetched: false },
    { query: "Italian dinner restaurants in colombo 4", fetched: false },
    { query: "best Chinese restaurants for dinner in colombo 4", fetched: false },
    { query: "fine dining Indian restaurants in colombo 5", fetched: false },
    { query: "elegant dinner restaurants in colombo 5", fetched: false },
    { query: "buffet restaurants in hotels colombo 5", fetched: false },
    { query: "best Mediterranean restaurants in colombo 5", fetched: false },
    { query: "French dinner restaurants colombo 5", fetched: false },
    { query: "Italian fine dining in colombo 5", fetched: false },
    { query: "seafood dinner restaurants in colombo 6", fetched: false },
    { query: "fine dining Sri Lankan cuisine in colombo 6", fetched: false },
    { query: "best hotel buffets for dinner in colombo 6", fetched: false },
    { query: "Japanese dinner restaurants in colombo 6", fetched: false },
    { query: "best Thai restaurants for dinner in colombo 6", fetched: false },
    { query: "Italian dinner restaurants colombo 6", fetched: false },
    { query: "top fine dining restaurants in colombo 7", fetched: false },
    { query: "luxury dinner restaurants with wine selection colombo 7", fetched: false },
    { query: "upscale buffet restaurants in colombo 7", fetched: false },
    { query: "best French restaurants in colombo 7", fetched: false },
    { query: "Italian fine dining in colombo 7", fetched: false },
    { query: "Japanese dinner restaurants colombo 7", fetched: false },
    { query: "best sit down dinner restaurants in colombo 8", fetched: false },
    { query: "exclusive hotel restaurants for dinner in colombo 8", fetched: false },
    { query: "fine dining with reservation in colombo 8", fetched: false },
    { query: "Mediterranean dinner restaurants colombo 8", fetched: false },
    { query: "French fine dining in colombo 8", fetched: false },
    { query: "Japanese dinner restaurants colombo 8", fetched: false },
    { query: "top-rated dinner restaurants in colombo 9", fetched: false },
    { query: "luxury buffets in hotels colombo 9", fetched: false },
    { query: "fine dining Sri Lankan restaurants colombo 9", fetched: false },
    { query: "Chinese fine dining in colombo 9", fetched: false },
    { query: "French dinner restaurants colombo 9", fetched: false },
    { query: "Italian dinner restaurants colombo 9", fetched: false },
    { query: "best fine dining experiences in colombo 10", fetched: false },
    { query: "hotel buffet restaurants for dinner in colombo 10", fetched: false },
    { query: "exclusive dinner restaurants with reservation colombo 10", fetched: false },
    { query: "Japanese fine dining in colombo 10", fetched: false },
    { query: "Italian dinner restaurants in colombo 10", fetched: false },
    { query: "best Mediterranean restaurants for dinner colombo 10", fetched: false },
    { query: "fine dining seafood restaurants in colombo 11", fetched: false },
    { query: "luxury dinner buffets in hotels colombo 11", fetched: false },
    { query: "romantic dinner places in colombo 11", fetched: false },
    { query: "French fine dining in colombo 11", fetched: false },
    { query: "Italian dinner restaurants colombo 11", fetched: false },
    { query: "Japanese dinner restaurants colombo 11", fetched: false },
    { query: "elegant restaurants for dinner in colombo 12", fetched: false },
    { query: "hotel buffets with dinner service colombo 12", fetched: false },
    { query: "fine dining Indian cuisine colombo 12", fetched: false },
    { query: "best Thai restaurants for dinner in colombo 12", fetched: false },
    { query: "French fine dining in colombo 12", fetched: false },
    { query: "Italian dinner restaurants colombo 12", fetched: false },
    { query: "fine dining restaurants for special occasions colombo 13", fetched: false },
    { query: "luxury buffets in hotels colombo 13", fetched: false },
    { query: "best upscale dinner restaurants colombo 13", fetched: false },
    { query: "Japanese dinner restaurants colombo 13", fetched: false },
    { query: "French fine dining in colombo 13", fetched: false },
    { query: "Italian dinner restaurants colombo 13", fetched: false },
    { query: "romantic dinner restaurants with reservation colombo 14", fetched: false },
    { query: "fine dining seafood restaurants colombo 14", fetched: false },
    { query: "best hotel buffets for dinner colombo 14", fetched: false },
    { query: "Italian dinner restaurants colombo 14", fetched: false },
    { query: "French fine dining in colombo 14", fetched: false },
    { query: "Japanese dinner restaurants colombo 14", fetched: false },
    { query: "exclusive dinner restaurants in colombo 15", fetched: false },
    { query: "hotel buffet restaurants in colombo 15", fetched: false },
    { query: "fine dining international cuisine colombo 15", fetched: false },
    { query: "Italian dinner restaurants colombo 15", fetched: false },
    { query: "French fine dining in colombo 15", fetched: false },
    { query: "Japanese dinner restaurants colombo 15", fetched: false }
]
